apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
  - app: mysql
spec:
  containers:
  - name: mysql
    image: 837853736685.dkr.ecr.us-east-1.amazonaws.com/app:1.0
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: pw
    ports:
    - containerPort: 3306